version: '3.4'

services:
  conferences.api:
    image: ${DOCKER_REGISTRY-}conferencesapi
    build:
      context: .
      dockerfile: Services/Conferences.Api/Dockerfile
    ports:
    - 8000:8000
    - 9000:9000

  eventstore.api:
    image: ${DOCKER_REGISTRY-}eventstoreapi
    build:
      context: .
      dockerfile: EventStore/EventStore.Api/Dockerfile
    ports:
    - 8001:8001
    - 9001:9001

  conferencesdb:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
     - 1433:1433
     environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: ExamplePassword123
       MSSQL_PID: EXPRESS

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"



  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8079:8079
      - 808
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
